[network]
port = 40871
max_peers = 50

[network.bootstrap]
peers = []
max_attempts = 5
retry_interval_secs = 2
health_check_interval_secs = 30
min_connections = 1
max_connections = 8
preferred_region = ""

[network.bootstrap.backoff]
base_delay_secs = 2
max_delay_secs = 300
multiplier = 2.0
max_attempts = 5

[storage]
data_shards = 4
parity_shards = 2
max_file_size = 104857600  # 100MB
chunk_size = 1048576       # 1MB

[security]
key_algorithm = "secp256k1"
verify_integrity = true
encryption_strength = "aes256"

[logging]
level = "info"
format = "json"