[network]
port = 40871
discovery_enabled = true


[storage]
data_dir = "/home/user/dev/datamesh/cluster_test_20250712_004514/data/node_0/storage"
max_file_size = 104857600  # 100MB
replication_factor = 3

[database]
db_path = "/home/user/dev/datamesh/cluster_test_20250712_004514/data/node_0/datamesh.db"

[security]
encryption_enabled = true
audit_enabled = true
audit_log_path = "/home/user/dev/datamesh/cluster_test_20250712_004514/logs/node_0_audit.log"

[api]
enabled = true
host = "127.0.0.1"
port = 8080
max_request_size = 104857600

[monitoring]
enabled = true
metrics_interval_seconds = 5
health_check_interval_seconds = 10

[performance]
chunk_size = 65536
concurrent_uploads = 4
cache_size_mb = 64

[logging]
level = "info"
file_path = "/home/user/dev/datamesh/cluster_test_20250712_004514/logs/node_0.log"
