[network]
bootstrap_port = 40871
max_peers = 50
connection_timeout = 30

[storage]
max_file_size = "100MB"
chunk_size = "64KB"

[performance]
concurrent_uploads = 4
concurrent_downloads = 4

[logging]
level = "info"
target = "file"
